version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR
      - go build hello.go 
artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: build-artifact-name
  discard-paths: no
    