version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR
      - go build hello.go 

artifacts:
  files: '**/*'
  base-directory: $CODEBUILD_SRC_DIR
  name: build-artifact-name
  discard-paths: no